version: '3.5'
services:
  php:
    image: hakanxemik/laravel-kubernetes-backend:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - APP_KEY=base64:RQJC5GGB89E8JZ1N9WRGeMWIEPmyMxQVDeXp86EBXEw=
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
